server:
  port: 8080

spring:
  application:
    name: querypilot-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/querypilot}
    username: ${DB_USERNAME:querypilot}
    password: ${DB_PASSWORD:querypilot}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai/v1
  model: openai/gpt-oss-120b

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info